anvilco/spectaql

.npmignore
app/helpers/codify.js
app/helpers/mdLink.js
app/helpers/stripTrailing.js
app/helpers/ternary.js
app/lib/common.js
app/spectaql/augmenters.js
app/spectaql/compose-paths.js
app/spectaql/index.js
app/spectaql/type-helpers.js

Since we are not yet babelizing the source to any particular target, the syntax used must be compatible with Node 8, since we say we want to support it. Seems like the "optional chaining" (`foo?.bar`) was the only culprit, and is only supported natively [starting at Node 14](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility).
Tested using `nvm` on version `8.17.0`.
Fixes https://github.com/anvilco/spectaql/issues/6

Node 8 compatibility fixes

---

app/views/partials/layout/content.hbs
app/views/partials/layout/nav.hbs
app/views/partials/swagger/paths.hbs
examples/data/schema.txt

[Now](https://github.com/anvilco/spectaql/pull/9) that `showTagSummary` will no longer trigger errors, we ought to make it look good, too.
1. Removes the "accordion" effect in this case.
2. Puts the `<a>` tags back in the nav so that Traverse works.

Better looking showTagSummary mode: fix collapse, link, etc

---

app/spectaql/compose-paths.js
app/spectaql/type-helpers.js
package.json

The library was already attempting to respect the "documentedness" (i.e. "hidden or not-ness") of Fields, Types, etc, all over. However, when generating examples for Queries or Mutations whose return types were complex/non-scalar (e.g. `[String]` or `[String!]!'`) then that guarantee / respect was lost.
Simple bugfix, more or less.
Fixes https://github.com/anvilco/spectaql/issues/11

Newhouse/issue 11/proper example for query or mutation return type

---

app/helpers/isInputType.js
app/lib/common.js
app/spectaql/augmenters.js
app/spectaql/type-helpers.js
app/stylesheets/_schema.scss
app/views/partials/json-schema/enum.hbs
app/views/partials/json-schema/input-type.hbs
app/views/partials/json-schema/properties.hbs
app/views/partials/swagger/definition.hbs
examples/data/schema.txt

See the issue for more details: https://github.com/anvilco/spectaql/issues/13
- Fixes / adds support for `INPUT_TYPE`.
- Uses the `default` from the schema, if there is one (after looking for `example` first)
- Fixes a few little bugs
Fixes https://github.com/anvilco/spectaql/issues/13

Better support for input types + bug fixes

---

app/index.js
app/spectaql/graphql-loaders.js
app/spectaql/index.js
bin/spectaql.js
config-example.yml
package.json

Support arbitrary request headers in the CLI or YAML.
Closes https://github.com/anvilco/spectaql/issues/49

Arbitrary headers support

---

app/spectaql/index.js
config-example.yml
package.json
test/app/spectaql/index.test.js
test/helpers.js

One should not have to provide any of the things that are currently required regarding the `urlToParse`. But, because it's swaggerific, I will not just eliminate it completely from being provided, so something satisfactory can be provided even if it's not (probably) going to end up in the UI.
Addresses #50

Newhouse/issue 50/url errors

---

app/helpers/isUnionType.js
app/spectaql/augmenters.js
app/views/partials/json-schema/union-type.hbs
package.json
test/app/helpers/isUnion.test.js
test/app/spectaql/augmenters.test.js
yarn.lock

Sorta updates the changes done [here](https://github.com/anvilco/spectaql/pull/75) to use the built-in support added [here](https://github.com/charlypoly/graphql-to-json-schema/pull/36).

[1-min] union support is now baked into graphql-2-json-schema

---

app/spectaql/graphql-loaders.js
examples/data/schema.gql
package.json
yarn.lock

Fixes https://github.com/anvilco/spectaql/issues/83
For now, it's fixed in Anvil's fork of the `graphql-to-json-schema` until I can get the fix merged upstream.

Fix enum list default values

---

app/spectaql/augmenters.js
examples/data/metadata.json
package.json
test/app/spectaql/augmenters.test.js
yarn.lock

Our `apollo-server-plugin-introspection-metadata` needed to [be fixed](https://github.com/anvilco/apollo-server-plugin-introspection-metadata/pull/2) to support this...then there were some changes to be made here in SpectaQL after updating the package.
Fixes https://github.com/anvilco/spectaql/issues/84

Support INPUT_OBJECT metadata examples

---

app/index.js
app/lib/gruntConfig.js
bin/spectaql.js
config-example.yml
test/app/index.test.js

Allow for an additional JS file to be added to the JS `spectaql.min.js` bundle. 
Will address https://github.com/anvilco/spectaql/issues/160

Allow for additional JS file to be added to JS bundle

---

README.md

The npm develop command didn't work. Corrected it to `npm install` and `npm run develop`

minor fix to instructions in README on how to run

---

src/themes/default/javascripts/scroll-spy.js
src/themes/default/stylesheets/base.scss
src/themes/default/stylesheets/main.scss
src/themes/spectaql/stylesheets/main.scss

Fixes all the issues in #278 related to long names 
Closes #278

Fixes for long names

---

src/themes/default/javascripts/scroll-spy.js
src/themes/default/stylesheets/main.scss
src/themes/spectaql/stylesheets/main.scss

This will make the scroll-spy behave the same in firefox, chrome, etc. That is:
* Don't scroll unless the active item is out of view
* Scroll the sidebar to the center 
Additionally, this fixes a sidebar issue when you scroll the main panel all the way to the bottom.
Closes #298

Fix scroll spy + behavior at end

---

src/themes/default/javascripts/scroll-spy.js

It is currently possible to hide elements in the navigation (`hideInNav`) and/or the content section (`hideInContent`). In case a type is hidden in the navigation but visible in the content, the scroll spy selects the link in the content as target. This leads to "jumps". The PR resolves this by limiting the scroll spy targets to the `#nav` element.

Limit Scroll Spy to Navigation Elements

---

src/lib/common.js

A root operation that returns a list returns a JSON array as result. For example, the definition
```
type Query {
machines: [Machine]
}
```
should have an example response like
```
{
"data": {
"machines": [
{ "machineId":  1234 }
]
}
}
```
but currently generates
```
{
"data": {
"machines": {
"machineId":  1234
}
}
}
```
This PR fixes this, by checking whether the return type is a list. It also accounts for non-nullable values.

Return a JSON Array for List Return Types

---

src/themes/default/stylesheets/base.scss

I have a CSS formatter that applied some things - let me know if you want me to change it back.
Super simple, applies the scroll offset to the html element so it applies the padding-top to all scroll actions (e.g. click). There are some hacks to make it apply to `body` or other elements, but it's recommended to use `html`:
https://webplatform.news/issues/2019-03-19#the-css-scroll-padding-property-adjusts-a-scroll-container-s-optimal-viewing-region
https://stackoverflow.com/a/60470570/5238640
https://css-tricks.com/fixed-headers-on-page-links-and-overlapping-content-oh-my/ - see note @ bottom

apply scroll padding top to html

---

src/lib/gruntConfig.js

Fixes https://github.com/anvilco/spectaql/issues/352

load main.css before other css files to preserve import behavior

---

examples/themes/README.md
src/themes/basic/stylesheets/main.scss
src/themes/default/stylesheets/custom.scss
src/themes/default/stylesheets/main.scss
src/themes/spectaql/stylesheets/main.scss

This allows for the User to just put their customizations in that file so they don't need to override the `main.scss` file, and miss out on updates.

Add `custom.scss` file to default theme

---

LICENSE

Similar to what Facebook did for react you should be able to just remove the year from the license to avoid updating constantly (https://github.com/facebook/react/pull/13593)

Remove year from copyright

---

src/spectaql/generate-graphql-example-data.js

check for lengthy fields array when determining fragmenting style in expansion
Closes https://github.com/anvilco/spectaql/issues/385

check for lengthy fields array when determining fragmenting style in expansion

---

src/themes/default/stylesheets/base.scss
src/themes/default/stylesheets/main.scss
src/themes/default/views/partials/layout/nav/mobile-navbar.hbs
src/themes/default/views/partials/layout/page.hbs
src/themes/spectaql/stylesheets/main.scss

Accessibility fixes for generated documentation

---

src/spectaql/directive.js

fixes #461 by providing a default fallback of `String()` when parsing directive values for `example` and `examples`

Add fallback parsing for example in directive

---

CHANGELOG.md
README.md
config-example.yml
src/index.js
src/spectaql/utils.js
test/src/index.test.js

Closes https://github.com/anvilco/spectaql/issues/492

run optionally returns output

---

.github/workflows/lint-and-test.yml
CHANGELOG.md
bin/build-vendor.mjs
package.json

Fixes https://github.com/anvilco/spectaql/issues/605

fix exit code

---

src/spectaql/index.js

When running SpectaQL on Windows, because `path.normalize` returns the absolute path to the file, the following error happens. . We can solve this by using `url`'s handy `pathToFileURL` function which does exactly what we need. 
```D:\p4\ci\main\datahub\node_modules\spectaql\dist\themes\default\data\index.js
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'd:'
at new NodeError (node:internal/errors:393:5)
at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1026:11)
at defaultResolve (node:internal/modules/esm/resolve:1106:3)
at nextResolve (node:internal/modules/esm/loader:163:28)
at ESMLoader.resolve …
```

Fix SpectaQL not working on Windows

---

CHANGELOG.md
config-example.yml
examples/data/schema.gql
package.json
src/index.js
src/spectaql/build-schemas.js
src/spectaql/graphql-loaders.js
src/themes/default/views/partials/graphql/kinds/input-object.hbs
test/src/index.test.js
test/src/spectaql/index.test.js
vendor-src/resource-embedder/package.json

Support for `@deprecated` on fields on `InputType`s.
Fixes https://github.com/anvilco/spectaql/issues/827

support deprecation on InputType fields

---

src/themes/default/javascripts/scroll-spy.js

Hi,
There is an issue with the scroll-spy from the default theme.
When you have multiple nav items that share a common root, the scroll spy will always select the first one due to the `'#nav a[href*=' + section.id + ']'` fuzzy selector for the `nextEl`.
Example in my case:
1 nav item has `href="#definition-ActivityAlertClassification"`  
1 nav item, lower in the tree, has `href="#definition-ActivityAlert"`
When scrolling past `definition-ActivityAlert`, the current scroll spy will incorrectly select `definition-ActivityAlertClassification` in the nav as it's the first match.
**Solution**
Switching to an exact value match `'#nav a[href="#' + section.id + '"]'` fixed the issue.  
If there was a specific reason for the previous query selector, happy to change the solution to support that use …

FIX incorrect hashtag selection in default theme

---

.github/dependabot.yml
vendor-src/grunt-compile-handlebars/package.json
vendor-src/grunt-embed/package.json
vendor-src/resource-embedder/package.json

Some stuff in these dependencies needed manual updating or was breaking in Node 14, etc.

[1-min] manual dependency updates

---

CHANGELOG.md
package.json
src/lib/common.js
src/themes/spectaql/stylesheets/main.scss
yarn.lock

Fixes https://github.com/anvilco/spectaql/issues/979

pin cheerio dep and fix deprecatd css warning

---

src/lib/common.js

As documented [1], cheerio will wrap output in
`<html><head></head><body>...</body></html>`. These fragments show up in various places in generated files. Call `load()` with the documented arguments to avoid this.
[1] https://cheerio.js.org/docs/basics/loading

Prevent stray html/head/body elements
