anvilco/spectaql

app/views/partials/swagger/path.hbs
=> Fix path to operation partial

app/helpers/isEnum.js, app/stylesheets/_schema.scss, app/views/partials/json-schema/datatype.hbs, app/views/partials/json-schema/enum.hbs, app/views/partials/swagger/definition.hbs, examples/data/schema.txt, package.json, yarn.lock
Better visual support for `ENUM` types.
Fixes https://github.com/anvilco/spectaql/issues/14
=> support ENUM better

app/views/partials/swagger/introduction/welcome.hbs
In regards to issue #42 I've added the contact and license information to the sidebar
=> Add contact and license information to sidebar

app/helpers/and.js, app/helpers/isInputType.js, app/spectaql/type-helpers.js
Updated some tricky array areas.
Converted type-helpers to 2 spaces.
=> Update some array things

app/lib/common.js
=> cheerio.load instead of cheerio()

app/index.js, package.json, test/app/index.test.js, yarn.lock
Fixes https://github.com/anvilco/spectaql/issues/57
=> Apply defaults correctly

package.json, yarn.lock
Fixes https://github.com/anvilco/spectaql/issues/1
=> Update and adjust dependencies and resolutions to remove vulns

package-lock.json, package.json, yarn.lock
It was out of date compared to `yarn.lock`
=> Update package lock

app/helpers/concat.js, app/helpers/md.js, app/helpers/not.js, app/lib/common.js, app/spectaql/augmenters.js, app/spectaql/compose-paths.js, app/spectaql/type-helpers.js, app/stylesheets/_layout.scss, app/stylesheets/_schema.scss, app/stylesheets/_utils.scss, app/stylesheets/_variables.scss, app/views/partials/json-schema/enum.hbs, app/views/partials/json-schema/properties.hbs, app/views/partials/swagger/operations/operation.hbs, config-example.yml, examples/data/schema.gql, yarn.lock
Fixes https://github.com/anvilco/spectaql/issues/18
=> Support @deprecated

README.md, app/helpers/isScalar.js, app/lib/common.js, app/spectaql/augmenters.js, bin/generateExampleData.js, examples/config.yml, examples/customizations/examples/index.js, examples/data/introspection-with-metadata.json, examples/data/introspection-without-metadata.json, examples/data/metadata.json, examples/data/schema.gql, package.json, test/app/helpers/isScalar.test.js, test/app/lib/common.test.js, test/app/spectaql/augmenters.test.js, test/fixtures/examplesProcessor.js
Fixes https://github.com/anvilco/spectaql/issues/60
=> Support metadata examples for customs Scalars

app/spectaql/compose-paths.js, app/spectaql/generate-example.js, app/views/partials/graphql/query-mutation-arguments.hbs, app/views/partials/swagger/operations/operation.hbs, test/app/spectaql/compose-paths.test.js
Fixes https://github.com/anvilco/spectaql/issues/85
=> Respect undocumented query/mutation Args

README.md, app/helpers/interpolateReferences.js, app/views/partials/graphql/field-arguments.hbs, app/views/partials/graphql/query-mutation-arguments.hbs, app/views/partials/json-schema/body.hbs, app/views/partials/json-schema/enum.hbs, app/views/partials/json-schema/input-type.hbs, app/views/partials/json-schema/properties.hbs, app/views/partials/json-schema/union-type.hbs, app/views/partials/swagger/deprecated/tags.hbs, app/views/partials/swagger/introduction/x-introItem.hbs, app/views/partials/swagger/operations/operation.hbs, app/views/partials/swagger/request-body.hbs, app/views/partials/swagger/securityDefinitions.hbs, app/views/partials/swagger/tags.hbs, app/views/partials/swagger/x-spectacle-topics.hbs, examples/data/schema.gql, test/app/helpers/interpolateReferences.test.js
=> Add support for reference interpolation

app/spectaql/graphql-loaders.js, test/app/spectaql/graphql-loaders.test.js, test/fixtures/non-standard-query-mutation-schema.gql, test/helpers.js
Addresses https://github.com/anvilco/spectaql/issues/5
=> Support non-standard query and mutation types

app/spectaql/augmenters.js, app/spectaql/type-helpers.js, examples/data/schema.gql, package.json, test/app/spectaql/index.test.js, test/helpers.js, yarn.lock
Some screwed up https://github.com/anvilco/spectaql/pull/112 and closed it by accident...
=> support interfaces

app/views/partials/swagger/operations/operation.hbs, package.json
Fixes https://github.com/anvilco/spectaql/issues/134
=> Fix mismatched h tags

app/index.js, app/lib/preprocessor.js, app/spectaql/index.js, examples/data/schema.gql
Addresses https://github.com/anvilco/spectaql/issues/151
=> Support query and mutation descriptions

.github/workflows/test.yml
Let's get some CI testing in there...
=> Add test.yml

app/spectaql/augmenters.js, app/spectaql/type-helpers.js, customizations/examples/index.js, examples/customizations/examples/index.js, test/app/spectaql/augmenters.test.js, test/fixtures/examplesProcessor.js
Add an `inputFieldProcessor` hook.
Addresses https://github.com/anvilco/spectaql/issues/147
=> add inputFieldProcessor

examples/data/schema.gql, package.json, yarn.lock
Fixes https://github.com/anvilco/spectaql/issues/186
=> allow complex default values

app/spectaql/graphql-loaders.js, app/spectaql/pre-process.js, app/spectaql/utils.js
Addresses, eventually, https://github.com/anvilco/spectaql/issues/211
=> Helpful message when unsupported schema file extension

src/lib/common.js, src/spectaql/generate-graphql-example-data.js, src/spectaql/utils.js
fix arg indentation and enum quoting
=> fix arg indentation

BREAKING_CHANGES_1.md, examples/config.yml, src/index.js, src/spectaql/build-schemas.js, test/src/index.test.js
Fix unnecessary path resolutions
=> Fix unnecessary path resolutions

CHANGELOG.md, package.json, src/index.js
Should fix https://github.com/anvilco/spectaql/issues/258
=> FIx path resolution

src/index.js, src/lib/gruntConfig.js, src/spectaql/index.js, src/spectaql/utils.js
Related to https://github.com/anvilco/spectaql/issues/257
=> fix path resolutions

src/spectaql/graphql-loaders.js
support globs in schemaFile loading
=> support globs in schemaFile loading

examples/data/schema.gql, package.json, src/lib/common.js, src/themes/default/helpers/graphql-scalars.js
Fixes https://github.com/anvilco/spectaql/issues/262
=> Fix some grapqlscalar examples

src/lib/common.js, test/src/lib/common.test.js
Fixes https://github.com/anvilco/spectaql/issues/265
=> Examples bug

config-example.yml, examples/config.yml, src/spectaql/generate-graphql-example-data.js, src/spectaql/graphql-loaders.js, src/spectaql/index.js, src/spectaql/pre-process.js, src/spectaql/utils.js
Fixes https://github.com/anvilco/spectaql/issues/277
=> Added support for various query name case strategies.

examples/customizations/examples/index.js, examples/data/metadata.json, src/lib/common.js, src/spectaql/augmenters.js, src/spectaql/generate-graphql-example-data.js, test/src/spectaql/augmenters.test.js
Fixes https://github.com/anvilco/spectaql/issues/279
=> Add back support for scalar type metadata examples

CHANGELOG.md, src/cli.js, src/index.js
Fixes https://github.com/anvilco/spectaql/issues/280
=> fix CLI --themeDir bug

CHANGELOG.md, README.md, examples/data/schema.gql, src/themes/default/helpers/interpolateReferences.js, test/src/helpers/interpolateReferences.test.js
Fixes https://github.com/anvilco/spectaql/issues/281
=> fixed reference interpolation

CHANGELOG.md, package.json, src/spectaql/utils.js
Hopefully will put https://github.com/anvilco/spectaql/issues/258 to bed.
=> fix windows/absolute path bug

config-example.yml, examples/config.yml, src/index.js, src/spectaql/generate-graphql-example-data.js, src/spectaql/index.js, src/spectaql/pre-process.js
Taking the work from https://github.com/anvilco/spectaql/pull/300 and re-doing it since they do not have time.
=> field expansion depth

examples/themes/README.md, src/themes/default/stylesheets/base.scss, src/themes/default/stylesheets/custom.scss, src/themes/default/stylesheets/main.scss, src/themes/default/stylesheets/syntax-highlighting.scss, src/themes/spectaql/stylesheets/main.scss
* More theme color vars
* Adds ability to override syntax theme
* More docs around theming
=> Improve theme system for easier overriding

examples/themes/README.md
Links the new blog post, new dark theme, and example usage repo
=> Add theme resources to theme readme

README.md
What it is should be above the fold here...
=> Move description up

package.json, src/index.js, yarn.lock
Tired of seeing this: https://github.com/anvilco/spectaql/security/dependabot/8
=> @anvilco/grunt-embed

examples/data/schema.gql, src/spectaql/generate-graphql-example-data.js, src/spectaql/graphql-hl.js, src/spectaql/pre-process.js
Fixes https://github.com/anvilco/spectaql/issues/405
From:
To:
=> support union inline fragments

examples/data/metadata.json, examples/data/schema.gql, package.json
Closes https://github.com/anvilco/spectaql/issues/436
=> [1-min] update apollo-server-plugin-introspection-metadata to support ENUM and INTERFACE. and add examples

CHANGELOG.md, config-example.yml, examples/data/schema.gql, examples/themes/my-partial-theme/data/index.js, package.json, src/index.js, src/spectaql/augmenters.js, src/spectaql/index.js, src/themes/default/data/index.js, test/src/spectaql/augmenters.test.js, yarn.lock
Fixes https://github.com/anvilco/spectaql/issues/437
=> allow all microfiber options to be provided. be consistent with passing them to all instances

CHANGELOG.md, src/index.js, src/lib/gruntConfig.js
Fixes https://github.com/anvilco/spectaql/issues/546
=> [1-min] watch the gql file to rebuild

CHANGELOG.md, src/lib/common.js, src/spectaql/augmenters.js, src/spectaql/utils.js, test/src/spectaql/index.test.js
Fixes https://github.com/anvilco/spectaql/issues/547
=> [1-min] allow anything but undefined examples

CHANGELOG.md, config-example.yml, src/lib/gruntConfig.js, src/themes/default/stylesheets/main.scss, src/themes/spectaql/stylesheets/main.scss
Addresses https://github.com/anvilco/spectaql/issues/508
=> [1-min] optional do not fetch font

BREAKING_CHANGES_2.md, bin/build-vendor.mjs, nodemon.json, package.json, src/themes/default/data/index.js, test/src/spectaql/index.test.js, vendor-src/.gitignore
Puts subscriptions in along with the other operations like queries and mutations.
Also adds cache file to detect whether to build vendor deps
=> subscriptions in operations

config-example.yml, src/index.js, test/src/index.test.js
Fixes https://github.com/anvilco/spectaql/issues/564
=> allow a few cli options in config

.github/dependabot.yml, .github/workflows/lint-and-test.yml, config-example.yml, nodemon.json, package.json, src/cli.js, src/index.js, src/spectaql/utils.js, test/e2e/alive.mjs, test/src/index.test.js, vendor-src/grunt-compile-handlebars/tasks/compile-handlebars.js, yarn.lock
Fixes https://github.com/anvilco/spectaql/issues/571
=> allow output to nowhere

src/lib/interpolation.js, src/lib/loadYaml.js, test/src/lib/interpolate.test.js
Addresses https://github.com/anvilco/spectaql/issues/197
=> env sub support

examples/data/schema.gql, src/spectaql/augmenters.js, src/spectaql/pre-process.js, test/src/spectaql/augmenters.test.js
Allow examples on types from the metadata.
Addresses https://github.com/anvilco/spectaql/issues/510
=> examples on types

src/themes/default/stylesheets/custom.scss, src/themes/default/stylesheets/main.scss
@benogle anything I should put there instead of barlow?
=> barlow removal

src/themes/default/views/partials/graphql/_description-with-defaults.hbs, src/themes/default/views/partials/graphql/_query-or-mutation-arguments.hbs, src/themes/default/views/partials/graphql/kinds/_fields.hbs, src/themes/default/views/partials/graphql/kinds/input-object.hbs
Fixes https://github.com/anvilco/spectaql/issues/484
=> render default values for fields on more things

CHANGELOG.md, package.json, yarn.lock
=> [1-min] 2.0.4

.github/workflows/lint-and-test.yml, yarn.lock
Smoke test for https://github.com/anvilco/spectaql/issues/732
=> [1-min] ensure that `npm install` works

yarn.lock
=> Revert "Bump @babel/core from 7.20.12 to 7.21.4"

src/themes/default/views/partials/layout/content/introduction/welcome.hbs
Adds the contact URL to the sidebar.
=> Add contact URL

CHANGELOG.md, config-example.yml, package.json, src/index.js, src/spectaql/index.js, src/spectaql/utils.js, src/themes/default/views/partials/layout/head.hbs, src/themes/default/views/partials/layout/page.hbs, test/src/index.test.js
Fixes https://github.com/anvilco/spectaql/issues/807
=> Better logo and Favicon support

package.json
Fixes https://github.com/anvilco/spectaql/issues/970
=> build vendor stuff during development command

src/spectaql/generate-graphql-example-data.js
- it seems typo was fixed in #341, but some constants were left unfixed.
=> fix typo 'STATEGY -> STRATEGY'
